"""
FOMO Email Utilities - Generate and send FOMO/re-engagement emails

This module contains everything for FOMO emails:
- Email templates and HTML generation
- Video thumbnail generation
- Rotating greeting/closing phrases
- Commander quotes via Claude AI
- One-click action links

Usage:
    from utilities.fomo_email_utils import send_fomo_email_to_user

    # Send preview to test email
    result = send_fomo_email_to_user(user_id=45, test_mode=True)

    # Send to real user
    result = send_fomo_email_to_user(user_id=45, test_mode=False)
"""

import logging
import random
from typing import Dict, List, Optional
from datetime import datetime, timezone

from utilities.postgres.core import db_cursor
from utilities.postgres.notifications import get_user_fomo_data
from utilities.postgres.users import get_user_by_id, get_user_by_email, get_all_users
from utilities.email.transport import send_simple_email
from utilities.email.actions import generate_action_url
from utilities.video_utils import get_user_video_data

logger = logging.getLogger(__name__)

__all__ = [
    'send_welcome_back_email',
    'generate_fomo_email_data',
    'send_fomo_email_to_user',
    'calculate_days_away',
    'get_fomo_greeting',
    'get_fomo_closing',
    'EMAIL_ASSETS',
    'FOMO_GREETING_PHRASES',
    'FOMO_CLOSING_PHRASES',
]

# ==============================================================================
# FOMO EMAIL ASSETS AND CONSTANTS
# ==============================================================================

# Email assets hosted on GCS (generated by tools/generate_email_assets.py)
EMAIL_ASSETS = {
    'mars_banner_header': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/mars_banner_header_v2.jpg',
    'icon_legendary': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/icon_legendary.png',
    'icon_rare': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/icon_rare.png',
    'icon_explorers': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/icon_explorers.png',
    'icon_discovery': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/icon_discovery.png',
    'icon_shards': 'https://storage.googleapis.com/galactica-pilgrim-assets/email_assets/icon_shards.png',
}

# Rotating casual greeting phrases for FOMO emails (no guilt-tripping about days away!)
# These rotate based on user_id to keep it consistent per-user
FOMO_GREETING_PHRASES = [
    "Just checking in—everything's running smoothly since we last saw you on",
    "Quick update! Things have been humming along nicely since your visit on",
    "Good news from Mars! The colony's been doing great since",
    "Hey there! Just wanted to let you know all systems are go since",
    "Friendly update: your crew's been keeping busy since you stopped by on",
    "All quiet on the Martian front since your last visit on",
    "Your colony is thriving! Here's what's been happening since",
    "Hope you're doing well! The team's been hard at work since",
    "Greetings from Mars! Everything's on track since we saw you on",
    "Just a quick hello—things are chugging along since",
]

# Rotating casual sign-off phrases for the video section (letter-style endings)
FOMO_CLOSING_PHRASES = [
    ("Signing Off", "That's all for now! We're cruising along just fine. Here's a quick clip of what we've been up to:"),
    ("Until Next Time", "Wishing you well from the red planet. Stop by anytime! Here's a little glimpse of life at the colony:"),
    ("Take Care", "We'll keep the lights on for you. Come back whenever you're ready! In the meantime, here's what we're up to:"),
    ("Cheers from Mars", "All is well here. Hope to see you soon! Here's a quick look at the crew in action:"),
    ("Over and Out", "That's the latest from base camp. Swing by anytime! Here's a peek at what's happening:"),
    ("Warmly", "Thanks for reading! The colony's doing great. Here's a little video update from the team:"),
    ("Best Wishes", "We're thinking of you back on Earth. Visit us when you can! Here's what the crew's been doing:"),
    ("From the Colony", "That wraps up our update. Drop in whenever! Here's a quick clip from the Martian frontier:"),
    ("See You Soon", "No rush—we'll be here! Just wanted to share this little moment from the colony:"),
    ("Safe Travels", "Wherever you are, we hope you're well. Here's a glimpse of daily life on Mars:"),
]

def get_fomo_greeting(user_id: int, last_login_str: str) -> str:
    """Get a rotating greeting phrase based on user_id for consistency."""
    import random
    # Use user_id as seed for consistent phrase per user
    random.seed(user_id)
    phrase = random.choice(FOMO_GREETING_PHRASES)
    random.seed()  # Reset seed
    return f"{phrase} <strong style='color: #ffcccc;'>{last_login_str}</strong>"

def get_fomo_closing(user_id: int) -> tuple:
    """Get a rotating closing phrase (header, description) based on user_id."""
    import random
    random.seed(user_id)
    header, desc = random.choice(FOMO_CLOSING_PHRASES)
    random.seed()
    return header, desc



def calculate_days_away(last_login) -> int:
    """Calculate days since last login."""
    if not last_login:
        return 0

    if isinstance(last_login, str):
        last_login = datetime.fromisoformat(last_login.replace('Z', '+00:00'))
    if last_login.tzinfo is None:
        last_login = last_login.replace(tzinfo=timezone.utc)

    now = datetime.now(timezone.utc)
    return (now - last_login).days


# ==============================================================================
# FOMO EMAIL HTML GENERATION
# ==============================================================================

def send_welcome_back_email(to_email: str, user_name: str, days_away: int, pending_items: Dict, fomo_data: Dict = None, action_links: Dict = None, video_data: Dict = None) -> bool:
    """
    Nudge inactive users to return with compelling FOMO hooks.

    Builds a context dict and renders templates/emails/welcome_back.html.
    Every conditional section (commander quote, sepolia harvest, discoveries,
    scientist lab, active/suggested expeditions, depot upgrades, global stats,
    legacy stats, video) is rendered by Jinja {% if %} blocks.

    fomo_data / action_links / video_data shapes: see generate_fomo_email_data.
    """
    from flask import render_template
    from datetime import datetime, timezone

    fomo_data = fomo_data or {}
    action_links = action_links or {}
    pending_items = pending_items or {}

    def fmt(n):
        """Format number with commas, 1 decimal if float."""
        if isinstance(n, float):
            return f"{n:,.1f}"
        return f"{n:,}"

    # ----- Subject line -----
    infra_generated = fomo_data.get('infrastructure_generated', 0)
    goal = fomo_data.get('next_goal')
    goal_needed = goal.get('needed', 0) if goal else 0

    subject_parts = []
    if infra_generated > 0:
        subject_parts.append(f"{fmt(infra_generated)} Sepolia Shards")
    if pending_items.get('discoveries', 0) > 0:
        subject_parts.append(f"{pending_items['discoveries']} Mars Discoveries")
    if pending_items.get('expeditions', 0) > 0:
        subject_parts.append(f"{pending_items['expeditions']} Expeditions")

    if subject_parts:
        subject = f"{user_name}, {' | '.join(subject_parts)} await!"
    elif goal and goal_needed > 0:
        subject = f"{user_name}, {fmt(goal_needed)} Sepolia Shards from {goal['name']}"
    else:
        subject = f"{user_name}, your Mars colony misses you"

    # ----- Header / greeting -----
    last_login = fomo_data.get('last_login')
    last_login_str = last_login.strftime('%b %d, %Y at %I:%M %p') if last_login else 'Unknown'
    user_id = fomo_data.get('user_id', 0)
    greeting_text = get_fomo_greeting(user_id, last_login_str)

    ctx = {
        'subject': subject,
        'user_name': user_name,
        'user_id': user_id,
        'greeting_text': greeting_text,
        'mars_banner': EMAIL_ASSETS['mars_banner_header'],
        'icons': {
            'legendary': EMAIL_ASSETS['icon_legendary'],
            'rare': EMAIL_ASSETS['icon_rare'],
            'explorers': EMAIL_ASSETS['icon_explorers'],
            'discovery': EMAIL_ASSETS['icon_discovery'],
            'shards': EMAIL_ASSETS['icon_shards'],
        },
        'pending_expeditions_count': pending_items.get('expeditions', 0),
    }

    # ----- Commander quote box -----
    commander = fomo_data.get('commander')
    if commander and commander.get('name'):
        commander_name = commander.get('name') or 'Captain'
        commander_stats = commander.get('stats') or {}
        active_expeditions_raw = fomo_data.get('active_expeditions', [])
        suggested_destinations_raw = fomo_data.get('suggested_destinations', [])
        total_expeditions = fomo_data.get('expedition_stats', {}).get('total', 0)

        try:
            from utilities.claude_utils import generate_commander_quote
            commander_quote = generate_commander_quote(
                commander_name=commander_name,
                stats=commander_stats,
                active_expeditions=active_expeditions_raw,
                suggested_destinations=suggested_destinations_raw,
                total_expeditions=total_expeditions,
            )
            if user_id:
                try:
                    from utilities.postgres.notifications import save_commander_quote
                    dest_name = None
                    if active_expeditions_raw:
                        dest_name = active_expeditions_raw[0].get('destination_name')
                    elif suggested_destinations_raw:
                        dest_name = suggested_destinations_raw[0].get('name')
                    save_commander_quote(user_id, commander_name, commander_quote, 'email', {
                        'stats': commander_stats,
                        'destination': dest_name,
                        'total_expeditions': total_expeditions,
                    })
                except Exception as save_err:
                    logger.warning(f"Failed to save commander quote: {save_err}")
        except Exception as quote_err:
            logger.warning(f"Failed to generate commander quote: {quote_err}")
            commander_quote = "The colony awaits our next move. Every expedition brings us closer to understanding this red planet."

        ctx['commander'] = {
            'name': commander_name,
            'image_url': commander.get('image_url') or '',
            'quote': commander_quote,
        }
    else:
        ctx['commander'] = None

    # ----- Sepolia harvest box -----
    if infra_generated > 0:
        from config_infrastructure import INFRASTRUCTURE_CATALOG
        harvest_url = action_links.get('claim_sepolia', '') or ''
        infra_breakdown_raw = fomo_data.get('infrastructure_breakdown', []) or []
        owned_infra = fomo_data.get('owned_infrastructure', {}) or {}
        current_balance = fomo_data.get('current_balance', 0) or 0

        sep = {
            'infra_generated_fmt': fmt(infra_generated),
            'harvest_url': harvest_url,
            'has_breakdown': bool(infra_breakdown_raw),
            'breakdown': [],
            'owned_grid': [],
            'owned_grid_rows': [],
            'next_upgrade': None,
            'maxed_out': False,
            'harvest_time_str': '',
            'daily_rate_fmt': '0',
            'weekly_rate_fmt': '0',
            'lifetime_harvested_fmt': '0',
        }

        daily_rate = 0
        if infra_breakdown_raw:
            oldest_payout = None
            for struct in infra_breakdown_raw:
                lp = struct.get('last_payout')
                if lp and (oldest_payout is None or lp < oldest_payout):
                    oldest_payout = lp

            if oldest_payout:
                if oldest_payout.tzinfo is None:
                    oldest_payout = oldest_payout.replace(tzinfo=timezone.utc)
                hours_ago = (datetime.now(timezone.utc) - oldest_payout).total_seconds() / 3600
                if hours_ago < 1:
                    sep['harvest_time_str'] = f"{int(hours_ago * 60)} minutes ago"
                elif hours_ago < 24:
                    sep['harvest_time_str'] = f"{int(hours_ago)} hours ago"
                else:
                    days_ago = int(hours_ago / 24)
                    sep['harvest_time_str'] = f"{days_ago} day{'s' if days_ago != 1 else ''} ago"
            else:
                sep['harvest_time_str'] = "Never harvested"

            total_hourly = sum(s.get('hourly_rate', 0) for s in infra_breakdown_raw)
            daily_rate = total_hourly * 24
            weekly_rate = daily_rate * 7
            lifetime_harvested = fomo_data.get('infrastructure_total_all_time', 0)

            sep['daily_rate_fmt'] = fmt(daily_rate)
            sep['weekly_rate_fmt'] = fmt(weekly_rate)
            sep['lifetime_harvested_fmt'] = fmt(lifetime_harvested)

            for struct in infra_breakdown_raw:
                struct_type = struct.get('structure_type', '')
                info = INFRASTRUCTURE_CATALOG.get(struct_type, {})
                sep['breakdown'].append({
                    'name': info.get('name', struct_type.replace('_', ' ').title()),
                    'icon': info.get('icon', '\u26a1'),
                    'pending_fmt': fmt(struct.get('pending', 0)),
                    'hourly_fmt': fmt(struct.get('hourly_rate', 0)),
                })

            # Owned infrastructure grid
            def _benefit(sid, sdata):
                resource = sdata.get('generates_resource')
                if sid == 'solar_array':
                    return (f"+{fmt(daily_rate)}/day", "#2ecc71", "\u26a1 Generating Sepolia")
                if sid == 'battery_storage':
                    return ("+50% night output", "#2ecc71", "\u26a1 Boosts Solar")
                if resource == 'water':
                    return ("-20% fuel costs", "#3498db", "\U0001f4a7 Fuel Synthesis")
                if resource == 'food':
                    rate = sdata.get('generation_rate', 0)
                    return (f"+{fmt(rate)}/hr", "#27ae60", "\U0001f331 Food Production")
                if sdata.get('effect') == 'expedition_capacity':
                    val = sdata.get('effect_value', 0)
                    return (f"+{val} expeditions", "#9b59b6", "\U0001f3e0 Crew Capacity")
                if sdata.get('effect') == 'discovery_bonus':
                    val = sdata.get('effect_value', 0)
                    return (f"+{int(val*100)}% discovery", "#e74c3c", "\U0001f4e1 Signal Boost")
                return (sdata.get('description', '')[:30], "#888", "\U0001f527 Active")

            display_order = ['solar_array', 'battery_storage', 'water_extractor', 'habitat_module', 'greenhouse', 'comms_array', 'refinery']
            for sid in display_order:
                if sid in owned_infra:
                    sdata = INFRASTRUCTURE_CATALOG.get(sid, {})
                    bt, bc, bl = _benefit(sid, sdata)
                    sep['owned_grid'].append({
                        'id': sid,
                        'name': sdata.get('name', sid),
                        'icon': sdata.get('icon', '\U0001f527'),
                        'image': sdata.get('image_url', ''),
                        'benefit_text': bt,
                        'benefit_color': bc,
                        'benefit_label': bl,
                    })

            # Chunk owned_grid into rows of 2 for template
            grid = sep['owned_grid']
            for i in range(0, len(grid), 2):
                row = [grid[i], grid[i+1] if i+1 < len(grid) else None]
                sep['owned_grid_rows'].append(row)

            # Next upgrade
            next_upgrade = None
            next_upgrade_id = None
            priority_order = ['battery_storage', 'water_extractor', 'habitat_module', 'greenhouse', 'comms_array', 'refinery']
            for sid in priority_order:
                if sid not in owned_infra:
                    sdata = INFRASTRUCTURE_CATALOG.get(sid)
                    if sdata and all(r in owned_infra for r in sdata.get('requirements', [])):
                        next_upgrade = sdata
                        next_upgrade_id = sid
                        break
            if not next_upgrade:
                for sid, sdata in INFRASTRUCTURE_CATALOG.items():
                    if sid not in owned_infra:
                        if all(r in owned_infra for r in sdata.get('requirements', [])):
                            next_upgrade = sdata
                            next_upgrade_id = sid
                            break

            if next_upgrade:
                level_1 = next_upgrade.get('levels', {}).get(1, {})
                upgrade_cost = int(level_1.get('cost', 0))
                can_afford = current_balance >= upgrade_cost
                upgrade_image = level_1.get('image_url', '')
                upgrade_icon = next_upgrade.get('icon', '\U0001f527')
                upgrade_resource = next_upgrade.get('generates_resource')

                if next_upgrade_id == 'battery_storage':
                    benefit_text = f"+50% night output \u2192 {fmt(daily_rate * 1.25)}/day"
                    benefit_color = "#2ecc71"
                    resource_label = "\u26a1 Boosts Sepolia"
                elif upgrade_resource == 'water':
                    benefit_text = "-20% expedition fuel costs"
                    benefit_color = "#3498db"
                    resource_label = "\U0001f4a7 Cheaper Expeditions"
                elif upgrade_resource == 'food':
                    benefit_text = "-25% life support costs"
                    benefit_color = "#27ae60"
                    resource_label = "\U0001f331 Grow Food"
                elif next_upgrade.get('effect') == 'expedition_capacity':
                    effect_val = next_upgrade.get('effect_value', 0)
                    benefit_text = f"+{effect_val} concurrent expeditions"
                    benefit_color = "#9b59b6"
                    resource_label = "\U0001f3e0 Crew Capacity"
                elif next_upgrade.get('effect') == 'discovery_bonus':
                    effect_val = next_upgrade.get('effect_value', 0)
                    benefit_text = f"+{int(effect_val*100)}% discovery chance"
                    benefit_color = "#e74c3c"
                    resource_label = "\U0001f4e1 Signal Boost"
                else:
                    benefit_text = next_upgrade.get('description', '')[:40]
                    benefit_color = "#888"
                    resource_label = "\U0001f527 Colony Upgrade"

                status_text = "\u2728 Ready to Build!" if can_afford else f"{fmt(current_balance)} / {fmt(upgrade_cost)}"
                status_color = "#f1c40f" if can_afford else "#888"
                border_color = "#f1c40f" if can_afford else "#444"
                bg_color = "rgba(241, 196, 15, 0.15)" if can_afford else "rgba(0,0,0,0.2)"
                btn_bg = "linear-gradient(135deg, #f1c40f 0%, #f39c12 100%)" if can_afford else "rgba(255,255,255,0.1)"
                btn_color = "#000" if can_afford else "#aaa"
                btn_label = "\U0001f528 Build Now" if can_afford else "\U0001f528 View Infrastructure"

                sep['next_upgrade'] = {
                    'name': next_upgrade['name'],
                    'icon': upgrade_icon,
                    'image': upgrade_image,
                    'benefit_text': benefit_text,
                    'benefit_color': benefit_color,
                    'resource_label': resource_label,
                    'status_text': status_text,
                    'status_color': status_color,
                    'border_color': border_color,
                    'bg_color': bg_color,
                    'btn_bg': btn_bg,
                    'btn_color': btn_color,
                    'btn_label': btn_label,
                }
            else:
                sep['maxed_out'] = True

        ctx['sepolia'] = sep
    else:
        ctx['sepolia'] = None

    # ----- Discoveries box -----
    discovery_count = pending_items.get('discoveries', 0)
    if discovery_count > 0:
        if discovery_count >= 100:
            teaser = "\u26a0\ufe0f Your storage is critically full! If you don't claim soon, we may have to jettison some to make room for new finds. Extract for shards or add to your collection now."
        elif discovery_count >= 50:
            teaser = "Your rover's cargo hold is nearly full. Claim these before your next expedition returns, or risk losing new discoveries to make space."
        elif discovery_count >= 10:
            teaser = "Each discovery can be extracted for Sepolia shards, or kept as part of your Martian collection. Don't let them pile up too long!"
        else:
            teaser = "Claim to add to your inventory, then extract for shards or keep the rare ones."

        pending_discoveries = fomo_data.get('pending_discoveries', []) or []
        unique = {}
        for disc in pending_discoveries:
            name = disc.get('item_name', 'Unknown')
            if name not in unique:
                unique[name] = {**disc, 'count': 1}
            else:
                unique[name]['count'] += 1
                unique[name]['enhanced_value'] = unique[name].get('enhanced_value', 0) + disc.get('enhanced_value', 0)
                unique[name]['scientific_value'] = unique[name].get('scientific_value', 0) + disc.get('scientific_value', 0)

        rarity_order = {'legendary': 0, 'rare': 1, 'uncommon': 2, 'common': 3}
        sorted_disc = sorted(unique.values(), key=lambda x: rarity_order.get(x.get('rarity', 'common'), 4))
        rarity_colors = {'legendary': '#f1c40f', 'rare': '#9b59b6', 'uncommon': '#3498db'}

        items = []
        for disc in sorted_disc[:3]:
            rarity = disc.get('rarity', 'common')
            desc = disc.get('description', '') or ''
            if len(desc) > 100:
                desc = desc[:97] + '...'
            count = disc.get('count', 1)
            ev = disc.get('enhanced_value', 0) or 0
            sv = disc.get('scientific_value', 0) or 0
            items.append({
                'item_name': disc.get('item_name', 'Unknown'),
                'rarity': rarity,
                'rarity_color': rarity_colors.get(rarity, '#888'),
                'image_url': disc.get('image_url') or '',
                'count_text': f' ({count}x)' if count > 1 else '',
                'description': desc,
                'enhanced_value_fmt': fmt(ev),
                'scientific_value': sv,
                'scientific_value_fmt': fmt(sv),
            })

        ctx['discoveries'] = {
            'count': discovery_count,
            'teaser': teaser,
            'claim_url': action_links.get('claim_discoveries', '') or '',
            'items': items,
        }
    else:
        ctx['discoveries'] = None

    # ----- Scientist / research lab -----
    scientist = fomo_data.get('scientist')
    research_points = fomo_data.get('research_points', 0) or 0
    total_scientific_value = fomo_data.get('total_scientific_value', 0) or 0

    if scientist:
        scientist_name = scientist.get('name', 'Your Scientist')
        scientist_specialty = scientist.get('specialty', 'Research')
        pending_disc_count = pending_items.get('discoveries', 0)
        pending_discoveries_list = fomo_data.get('pending_discoveries', []) or []
        latest_discovery_name = pending_discoveries_list[0].get('item_name') if pending_discoveries_list else None

        try:
            from utilities.claude_utils import generate_scientist_quote
            scientist_quote = generate_scientist_quote(
                scientist_name=scientist_name,
                specialty=scientist_specialty,
                total_scientific_value=total_scientific_value,
                research_points=research_points,
                pending_discoveries=pending_disc_count,
                latest_discovery=latest_discovery_name,
            )
        except Exception as quote_err:
            logger.warning(f"Failed to generate scientist quote: {quote_err}")
            scientist_quote = "The specimens you've brought back are remarkable. Each discovery adds to our understanding of Mars."

        if total_scientific_value >= 1000 and research_points == 0:
            sci_teaser = "Your discoveries contain ancient Martian crystals. Analyze them to extract Sepolia shards, or save rare specimens for the Xenobiology Lab."
        elif research_points > 0:
            sci_teaser = f"You have {research_points} research point{'s' if research_points != 1 else ''} ready to spend! Upgrade your captain's stats in the Xenobiology Lab."
        elif total_scientific_value > 0:
            sci_teaser = "Each discovery holds scientific secrets. Your scientist can analyze specimens to extract embedded Sepolia shards."
        else:
            sci_teaser = "Your scientist studies every artifact you bring back, searching for traces of ancient Martian life."

        ctx['scientist'] = {
            'name': scientist_name,
            'specialty': scientist_specialty,
            'image_url': scientist.get('image_url', '') or '',
            'quote': scientist_quote,
            'teaser': sci_teaser,
            'total_scientific_value_fmt': fmt(total_scientific_value),
            'research_points': research_points,
            'show_stats': total_scientific_value > 0 or research_points > 0,
        }
    else:
        ctx['scientist'] = None

    # ----- Expeditions: active OR suggested -----
    active_expeditions_raw = fomo_data.get('active_expeditions', []) or []
    suggested_destinations_raw = fomo_data.get('suggested_destinations', []) or []
    expedition_stats = fomo_data.get('expedition_stats', {}) or {}
    total_expeditions = expedition_stats.get('total', 0)

    def _gen_location_image(name):
        try:
            from tools.mars_location_image_generator import get_or_generate_location_image
            logger.info(f"Generating image on-demand for: {name}")
            return get_or_generate_location_image(name)
        except Exception as e:
            logger.warning(f"Could not generate image for {name}: {e}")
            return ''

    if active_expeditions_raw:
        active_list = []
        for exp in active_expeditions_raw:
            remaining = exp.get('remaining_seconds', 0) or 0
            progress = int(exp.get('progress_pct', 0) or 0)
            dest_name = exp.get('destination_name', 'Unknown')
            dest_image_url = exp.get('destination_image_url', '') or ''
            dest_link = exp.get('destination_link', '') or ''
            dest_lat = exp.get('destination_lat')
            dest_lon = exp.get('destination_lon')
            distance = exp.get('distance_km', 0) or 0

            if not dest_image_url and dest_name:
                dest_image_url = _gen_location_image(dest_name)

            coords_str = f"{dest_lat:.1f}\u00b0, {dest_lon:.1f}\u00b0" if (dest_lat is not None and dest_lon is not None) else ''
            if remaining > 3600:
                time_str = f"{remaining // 3600}h {(remaining % 3600) // 60}m"
            elif remaining > 60:
                time_str = f"{remaining // 60}m"
            elif remaining > 0:
                time_str = "Arriving soon!"
            else:
                time_str = "Ready to claim!"

            if dest_link:
                name_html = f'<a href="{dest_link}" target="_blank" style="color: #fff; text-decoration: none; border-bottom: 1px dotted #3498db;">{dest_name}</a>'
            else:
                name_html = dest_name

            active_list.append({
                'dest_name': dest_name,
                'dest_name_html': name_html,
                'dest_type': exp.get('destination_type', '') or '',
                'dest_image_url': dest_image_url,
                'distance_str': f"{distance:.0f} km from base",
                'coords_str': coords_str,
                'progress_pct': progress,
                'time_str': time_str,
            })
        ctx['active_expeditions'] = active_list
        ctx['suggested_destinations'] = None
        ctx['expedition_teaser'] = ''
        ctx['base_coords_str'] = ''
    elif suggested_destinations_raw and total_expeditions > 0:
        base_lat = fomo_data.get('colony_lat', -4.5)
        base_lon = fomo_data.get('colony_lon', 137.4)
        base_coords_str = f"{float(base_lat):.1f}\u00b0, {float(base_lon):.1f}\u00b0"

        ges = fomo_data.get('global_expedition_stats', {}) or {}
        user_discovery_pct = ges.get('user_discovery_pct', 0.0) or 0.0
        total_all_discoveries = ges.get('total_discoveries', 0) or 0
        competitor_pct = ges.get('competitor_pct', 0.0) or 0.0
        competitor_ahead = ges.get('competitor_ahead', True)

        if user_discovery_pct > 50:
            if competitor_pct > 0:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of all Martian artifacts. You're #1! Your closest rival has only {competitor_pct:.1f}% \u2014 maintain your lead!"
            else:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of all Martian artifacts. You're leading the expedition rankings \u2014 maintain your dominance!"
        elif user_discovery_pct > 20:
            if competitor_ahead and competitor_pct > 0:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of catalogued artifacts. Your closest competitor has <strong>{competitor_pct:.1f}%</strong> \u2014 you can catch them if you deploy now!"
            else:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of catalogued artifacts. A rival is closing in at {competitor_pct:.1f}% \u2014 don't let them overtake you!"
        elif user_discovery_pct > 5:
            if competitor_ahead and competitor_pct > 0:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of catalogued artifacts. The next captain ahead has {competitor_pct:.1f}% \u2014 a few expeditions could close that gap!"
            else:
                expedition_teaser = f"\U0001f4ca You've claimed <strong>{user_discovery_pct:.1f}%</strong> of catalogued artifacts. The remaining {100 - user_discovery_pct:.1f}% await discovery \u2014 don't let rivals claim them first."
        elif total_all_discoveries > 0:
            if competitor_ahead and competitor_pct > 0:
                expedition_teaser = f"\U0001f4ca You've claimed only <strong>{user_discovery_pct:.1f}%</strong> of known artifacts. Your closest competitor has {competitor_pct:.1f}% \u2014 deploy your rover to start climbing the ranks!"
            else:
                expedition_teaser = f"\U0001f4ca You've claimed only <strong>{user_discovery_pct:.1f}%</strong> of known artifacts. Other captains are building larger collections \u2014 your rover should be exploring!"
        else:
            expedition_teaser = "\U0001f4ca No artifacts have been catalogued yet. Be the first to explore these uncharted destinations and claim discovery credit!"

        suggested_list = []
        for dest in suggested_destinations_raw[:3]:
            dest_name = dest.get('name', 'Unknown')
            image_url = dest.get('image_url', '') or ''
            if not image_url and dest_name:
                image_url = _gen_location_image(dest_name)
            latitude = dest.get('latitude')
            longitude = dest.get('longitude')
            origin = dest.get('origin', '') or ''
            if not origin or 'albedo' in origin.lower():
                origin = "Origin unknown \u2014 awaiting exploration..."
            distance = dest.get('distance_km', 0) or 0
            usgs_link = dest.get('link', '') or ''

            explorer_count = dest.get('explorer_count', 0) or 0
            total_discoveries = dest.get('total_discoveries', 0) or 0
            legendary_finds = dest.get('legendary_finds', 0) or 0
            rare_finds = dest.get('rare_finds', 0) or 0

            if explorer_count == 0:
                badge = "\U0001f3c6 UNCHARTED \u2014 Be the first explorer!"
                badge_color = "#f1c40f"
            elif legendary_finds > 0:
                badge = f"\u2694\ufe0f {explorer_count} captain{'s' if explorer_count != 1 else ''} explored \u2022 {total_discoveries} finds ({legendary_finds} legendary!)"
                badge_color = "#e74c3c"
            elif rare_finds > 0:
                badge = f"\u2694\ufe0f {explorer_count} captain{'s' if explorer_count != 1 else ''} explored \u2022 {total_discoveries} finds ({rare_finds} rare)"
                badge_color = "#9b59b6"
            elif total_discoveries > 0:
                badge = f"\U0001f465 {explorer_count} captain{'s' if explorer_count != 1 else ''} explored \u2022 {total_discoveries} artifacts found"
                badge_color = "#3498db"
            else:
                badge = f"\U0001f465 {explorer_count} captain{'s' if explorer_count != 1 else ''} explored \u2022 More to discover!"
                badge_color = "#3498db"

            distance_str = f"{distance:,.0f} km from base" if distance else ''
            coords_str = f"{float(latitude):.1f}\u00b0, {float(longitude):.1f}\u00b0" if (latitude and longitude) else ''

            if usgs_link:
                name_html = f'<a href="{usgs_link}" target="_blank" style="color: #fff; text-decoration: underline; text-decoration-color: rgba(255,255,255,0.4);">{dest_name}</a>'
            else:
                name_html = dest_name

            suggested_list.append({
                'name': dest_name,
                'name_html': name_html,
                'type': dest.get('type', 'terrain'),
                'image_url': image_url,
                'origin': origin,
                'distance_str': distance_str,
                'coords_str': coords_str,
                'competition_badge': badge,
                'badge_color': badge_color,
            })

        ctx['active_expeditions'] = None
        ctx['suggested_destinations'] = suggested_list
        ctx['expedition_teaser'] = expedition_teaser
        ctx['base_coords_str'] = base_coords_str
    else:
        ctx['active_expeditions'] = None
        ctx['suggested_destinations'] = None
        ctx['expedition_teaser'] = ''
        ctx['base_coords_str'] = ''

    # ----- Depot upgrades mini-catalog -----
    from config_infrastructure import INFRASTRUCTURE_CATALOG
    balance = fomo_data.get('current_balance', 0) or 0
    owned_infrastructure = fomo_data.get('owned_infrastructure', {}) or {}

    def _get_next_infra(owned, bal):
        priority = ['battery_storage', 'water_extractor', 'habitat_module', 'greenhouse', 'comms_array', 'refinery']
        for sid in priority:
            if sid in owned:
                continue
            s = INFRASTRUCTURE_CATALOG.get(sid)
            if not s:
                continue
            if not all(r in owned for r in s.get('requirements', [])):
                continue
            lvl1 = s.get('levels', {}).get(1, {})
            return (sid, s, int(lvl1.get('cost', 0)))
        return None

    infra_upgrade = _get_next_infra(owned_infrastructure, balance)
    upgrades_to_show = []
    if infra_upgrade:
        sid, sdata, cost = infra_upgrade
        can_afford = balance >= cost
        upgrades_to_show.append({
            'category_label': '\U0001f3d7\ufe0f Colony Building',
            'category_color': '#2ecc71',
            'name': sdata.get('name'),
            'icon': sdata.get('icon', '\U0001f527'),
            'image_url': sdata.get('image_url', ''),
            'benefit': sdata.get('description', '')[:50],
            'cost': cost,
            'can_afford': can_afford,
            'border_color': '#f1c40f' if can_afford else '#444',
            'status_text': '\u2728 Ready!' if can_afford else f"{fmt(cost)} Shards",
            'status_color': '#f1c40f' if can_afford else '#888',
            'bg_color': 'rgba(241, 196, 15, 0.15)' if can_afford else 'rgba(0,0,0,0.2)',
        })

    ctx['upgrades_to_show'] = upgrades_to_show
    ctx['upgrade_col_width'] = f"{100 // max(len(upgrades_to_show), 1)}%"
    ctx['balance_fmt'] = fmt(balance)

    # ----- Global stats / Meanwhile on Mars -----
    global_stats = fomo_data.get('global_stats', {}) or {}
    legendary_week = global_stats.get('legendary_this_week', 0) or 0
    rare_week = global_stats.get('rare_this_week', 0) or 0
    if legendary_week > 0 or rare_week > 0:
        user_legendary = fomo_data.get('discovery_stats', {}).get('legendary', 0)
        ctx['global_block'] = {
            'legendary_this_week': legendary_week,
            'rare_this_week': rare_week,
            'active_commanders': global_stats.get('active_commanders', 0),
            'show_legendary_tease': user_legendary == 0 and legendary_week > 0,
        }
    else:
        ctx['global_block'] = None

    # ----- Legacy stats -----
    discovery_stats = fomo_data.get('discovery_stats', {}) or {}
    if discovery_stats.get('total', 0) > 0:
        ctx['legacy'] = {
            'total_fmt': fmt(discovery_stats.get('total', 0)),
            'rare_fmt': fmt(discovery_stats.get('rare', 0)),
            'legendary_fmt': fmt(discovery_stats.get('legendary', 0)),
            'total_value_fmt': fmt(discovery_stats.get('total_value', 0)),
        }
    else:
        ctx['legacy'] = None

    # ----- Video -----
    if video_data and video_data.get('thumbnail_url') and video_data.get('video_url'):
        closing_header, closing_desc = get_fomo_closing(user_id)
        ctx['video'] = {
            'thumbnail_url': video_data['thumbnail_url'],
            'video_url': video_data['video_url'],
            'captain_name': video_data.get('captain_name', 'Your captain'),
            'closing_header': closing_header,
            'closing_desc': closing_desc,
        }
    else:
        ctx['video'] = None

    # ----- Render -----
    # Use test_request_context so global template processors that expect a
    # request (e.g. session lookups in inject_global_stats) still work when
    # this is called from cron/CLI paths that only have an app context.
    def _render():
        return render_template('emails/welcome_back.html', **ctx)

    try:
        from flask import current_app
        _ = current_app.name  # raises if no app context
        try:
            rendered = _render()
        except RuntimeError:
            with current_app.test_request_context('/'):
                rendered = _render()
    except RuntimeError:
        from app import app
        with app.test_request_context('/'):
            rendered = _render()

    return send_simple_email(subject, rendered, to_email, is_html=True)

# ==============================================================================
# HIGH-LEVEL API
# ==============================================================================

def generate_fomo_email_data(user_id: int, secret_key: str = None) -> Dict:
    """
    Generate all data needed for a FOMO email.

    Returns dict with:
        - user: Basic user info
        - fomo_data: Full FOMO data from postgres_utils
        - pending_items: Summary of pending items
        - action_links: One-click action URLs (if secret_key provided)
        - video_data: Video thumbnail/URL data (if user has video)
        - days_away: Days since last login
    """
    # Get user info
    user = get_user_by_id(user_id)
    if not user:
        return {'error': f'User {user_id} not found'}

    # Get FOMO data
    fomo_data = get_user_fomo_data(user_id)
    if not fomo_data:
        return {'error': f'Could not get FOMO data for user {user_id}'}

    # Calculate next goal
    try:
        from tools.send_notifications import calculate_next_goal
        next_goal = calculate_next_goal(
            fomo_data.get('current_balance', 0),
            fomo_data.get('owned_upgrades', []),
            fomo_data.get('owned_infrastructure', {})
        )
        fomo_data['next_goal'] = next_goal
    except Exception as e:
        logger.warning(f"Could not calculate next goal: {e}")

    # Build pending items summary
    pending_items = {
        'expeditions': fomo_data.get('expedition_stats', {}).get('completed', 0),
        'discoveries': fomo_data.get('pending_discoveries_count', 0),
        'sepolia': fomo_data.get('infrastructure_generated', 0),
    }

    # Generate action links if secret key provided
    action_links = None
    if secret_key:
        action_links = {
            'claim_discoveries': generate_action_url(user_id, 'claim_discoveries', secret_key),
            'claim_sepolia': generate_action_url(user_id, 'claim_sepolia', secret_key),
        }

    # Calculate days away
    days_away = calculate_days_away(fomo_data.get('last_login'))

    # Get video data
    commander = fomo_data.get('commander')
    commander_name = commander.get('name') if commander else user.get('given_name') or user.get('name')
    video_data = get_user_video_data(user_id, commander_name)

    return {
        'user': user,
        'fomo_data': fomo_data,
        'pending_items': pending_items,
        'action_links': action_links,
        'video_data': video_data,
        'days_away': days_away,
        'user_name': user.get('given_name') or user.get('name') or 'Commander',
    }


def send_fomo_email_to_user(
    user_id: int,
    secret_key: str = None,
    test_mode: bool = False,
    test_recipient: str = "andy.tillo@gmail.com"
) -> Dict:
    """
    Generate and send a FOMO email to a user (or test recipient).

    Args:
        user_id: The user to generate the email for
        secret_key: Secret key for action links (optional)
        test_mode: If True, send to test_recipient instead of real user
        test_recipient: Email to send to in test mode

    Returns:
        Dict with 'success', 'message', and email details
    """
    # Generate all email data
    email_data = generate_fomo_email_data(user_id, secret_key)

    if 'error' in email_data:
        return {'success': False, 'message': email_data['error']}

    # Determine recipient
    user = email_data['user']
    to_email = test_recipient if test_mode else user.get('email')

    # Modify name in test mode to indicate it's a preview
    user_name = email_data['user_name']
    if test_mode:
        user_name = f"[PREVIEW: {user.get('email')}] {user_name}"

    # Send the email
    success = send_welcome_back_email(
        to_email=to_email,
        user_name=user_name,
        days_away=email_data['days_away'],
        pending_items=email_data['pending_items'],
        fomo_data=email_data['fomo_data'],
        action_links=email_data['action_links'],
        video_data=email_data['video_data']
    )

    return {
        'success': success,
        'message': f"Email {'sent' if success else 'failed'} to {to_email}",
        'to_email': to_email,
        'user_id': user_id,
        'has_video': email_data['video_data'] is not None,
        'pending_discoveries': email_data['pending_items'].get('discoveries', 0),
        'pending_sepolia': email_data['pending_items'].get('sepolia', 0),
        'days_away': email_data['days_away'],
    }
