#!/usr/bin/env python3
"""
update_default_image_video.py
Backfills missing character_video entries for users with default commanders
Matches default character images to their corresponding GCS-hosted videos
"""

import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from utilities.postgres_utils import (
    get_db_connection,
    create_replicate_asset
)
from config import BUCKET_NAME, DEFAULT_LEADERS_GCS_BASE

##############################################################################
# CONFIGURATION
##############################################################################

DRY_RUN = True  # Set to False to actually create video entries
BATCH_SIZE = 10  # Process this many users at a time

##############################################################################
# DEFAULT LEADER DETECTION
##############################################################################

def is_default_leader_image(gcs_url: str) -> bool:
    """Check if image URL is from default leaders"""
    if not gcs_url:
        return False
    
    # Check if URL matches default leaders pattern
    default_pattern = f"{BUCKET_NAME}/{DEFAULT_LEADERS_GCS_BASE}/images/"
    return default_pattern in gcs_url


def extract_leader_id_from_url(gcs_url: str) -> str:
    """
    Extract leader_id from default leader GCS URL
    Example: https://storage.googleapis.com/bucket/default_leaders/images/leader1_andy.png
    Returns: leader1_andy
    """
    if not gcs_url:
        return None
    
    try:
        # Get filename from URL
        filename = gcs_url.split('/')[-1]
        # Remove extension
        leader_id = filename.rsplit('.', 1)[0]
        return leader_id
    except:
        return None


def get_default_video_url(leader_id: str) -> str:
    """Generate GCS URL for default leader video"""
    return f"https://storage.googleapis.com/{BUCKET_NAME}/{DEFAULT_LEADERS_GCS_BASE}/videos/{leader_id}.mp4"


def get_default_video_blob(leader_id: str) -> str:
    """Generate GCS blob path for default leader video"""
    return f"{DEFAULT_LEADERS_GCS_BASE}/videos/{leader_id}.mp4"


##############################################################################
# MAIN LOGIC
##############################################################################

def find_users_needing_videos():
    """
    Find users with default character images but no corresponding videos
    
    Returns: List of (user_id, image_asset_id, leader_id, commander_name) tuples
    """
    conn = get_db_connection()
    cur = conn.cursor()
    
    query = """
    -- Find users with default character images
    WITH user_images AS (
        SELECT 
            user_id,
            id as image_asset_id,
            gcs_url,
            commander_name,
            created_at as image_created_at
        FROM pilgrim.replicate_assets
        WHERE asset_type = 'character_image'
          AND user_id IS NOT NULL
          AND gcs_url LIKE %s
          AND is_deleted = FALSE
    ),
    user_videos AS (
        SELECT DISTINCT user_id
        FROM pilgrim.replicate_assets
        WHERE asset_type = 'character_video'
          AND user_id IS NOT NULL
          AND is_deleted = FALSE
    )
    SELECT 
        ui.user_id,
        ui.image_asset_id,
        ui.gcs_url,
        ui.commander_name
    FROM user_images ui
    LEFT JOIN user_videos uv ON ui.user_id = uv.user_id
    WHERE uv.user_id IS NULL  -- No video exists
    ORDER BY ui.image_created_at DESC
    """
    
    # Pattern to match default leaders
    pattern = f"%{BUCKET_NAME}/{DEFAULT_LEADERS_GCS_BASE}/images/%"
    
    cur.execute(query, (pattern,))
    results = cur.fetchall()
    
    cur.close()
    conn.close()
    
    # Extract leader_id from each URL
    users_with_leaders = []
    for user_id, image_asset_id, gcs_url, commander_name in results:
        leader_id = extract_leader_id_from_url(gcs_url)
        if leader_id:
            users_with_leaders.append((user_id, image_asset_id, leader_id, commander_name))
    
    return users_with_leaders


def create_video_entry(user_id: int, image_asset_id: int, leader_id: str, commander_name: str) -> bool:
    """
    Create a character_video entry for a default leader
    
    Returns: True if successful
    """
    video_url = get_default_video_url(leader_id)
    video_blob = get_default_video_blob(leader_id)
    
    try:
        asset_id = create_replicate_asset(
            user_id=user_id,
            asset_type='character_video',
            replicate_url=None,  # Default videos weren't generated by Replicate
            gcs_url=video_url,
            gcs_blob_name=video_blob,
            parent_asset_id=image_asset_id,
            replicate_model='default-leader',
            content_type='video/mp4',
            commander_name=commander_name
        )
        
        return asset_id is not None
        
    except Exception as e:
        print(f"❌ Error creating video entry: {e}")
        return False


##############################################################################
# EXECUTION
##############################################################################

def main():
    print("="*70)
    print("DEFAULT LEADER VIDEO BACKFILL SCRIPT")
    print("="*70)
    print(f"Mode: {'DRY RUN (no changes)' if DRY_RUN else 'LIVE (will create entries)'}")
    print(f"Batch size: {BATCH_SIZE}")
    print("="*70)
    
    # Find users needing videos
    print("\n🔍 Searching for users with default commanders but no videos...")
    users_needing_videos = find_users_needing_videos()
    
    if not users_needing_videos:
        print("\n✅ No users need video backfill!")
        print("All default leader users already have videos.")
        return
    
    print(f"\n📊 Found {len(users_needing_videos)} user(s) needing videos:")
    print()
    
    # Show summary
    leader_counts = {}
    for user_id, image_asset_id, leader_id, commander_name in users_needing_videos:
        leader_counts[leader_id] = leader_counts.get(leader_id, 0) + 1
    
    print("By Leader:")
    for leader_id, count in sorted(leader_counts.items()):
        print(f"  - {leader_id}: {count} user(s)")
    
    print("\n" + "="*70)
    print("DETAILED LIST:")
    print("="*70)
    
    for idx, (user_id, image_asset_id, leader_id, commander_name) in enumerate(users_needing_videos[:20], 1):
        name_display = f" ({commander_name})" if commander_name else ""
        print(f"{idx}. User {user_id} | Asset {image_asset_id} | {leader_id}{name_display}")
    
    if len(users_needing_videos) > 20:
        print(f"... and {len(users_needing_videos) - 20} more")
    
    # Confirm action
    if DRY_RUN:
        print("\n" + "="*70)
        print("🔍 DRY RUN MODE - No changes will be made")
        print("="*70)
        print("\nTo execute for real, set DRY_RUN = False in the script")
        return
    
    print("\n" + "="*70)
    print("⚠️  WARNING: LIVE MODE")
    print("="*70)
    print(f"This will create {len(users_needing_videos)} video entries in the database.")
    print(f"Processing in batches of {BATCH_SIZE}.")
    
    response = input("\nType 'CREATE VIDEOS' to proceed: ")
    if response != 'CREATE VIDEOS':
        print("\n❌ Cancelled.")
        return
    
    # Process in batches
    print("\n" + "="*70)
    print("PROCESSING BATCHES")
    print("="*70)
    
    successful = 0
    failed = 0
    
    for batch_start in range(0, len(users_needing_videos), BATCH_SIZE):
        batch = users_needing_videos[batch_start:batch_start + BATCH_SIZE]
        batch_num = (batch_start // BATCH_SIZE) + 1
        total_batches = (len(users_needing_videos) + BATCH_SIZE - 1) // BATCH_SIZE
        
        print(f"\n📦 Batch {batch_num}/{total_batches} ({len(batch)} users)")
        
        for user_id, image_asset_id, leader_id, commander_name in batch:
            name_display = f" ({commander_name})" if commander_name else ""
            
            if create_video_entry(user_id, image_asset_id, leader_id, commander_name):
                print(f"  ✅ User {user_id} | {leader_id}{name_display}")
                successful += 1
            else:
                print(f"  ❌ User {user_id} | {leader_id}{name_display} - FAILED")
                failed += 1
    
    # Summary
    print("\n" + "="*70)
    print("BACKFILL COMPLETE")
    print("="*70)
    print(f"✅ Successful: {successful}")
    print(f"❌ Failed: {failed}")
    print(f"📊 Total processed: {successful + failed}")
    
    if successful > 0:
        print(f"\n🎉 Successfully created {successful} video entries!")
        print("Users can now see their commander videos in the colony interface.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️ Interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Fatal error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)